
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: petstoreee7
    name: petstoreee7
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - image: quay.io/myproject/petstoreee7:latest
                  imagePullPolicy: Always
                  name: petstoreee7
                  ports:
                    - containerPort: 8080
                  resources: {}
            restartPolicy: Always
status: {}

...
