apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: php
  name: php
spec:
  ports:
    - name: port-8082
      port: 8082
      targetPort: 8082
  selector:
    move2kube.konveyor.io/service: php
  type: ClusterIP
status:
  loadBalancer: {}
