apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: php
  name: php
spec:
  replicas: 2
  selector:
    matchLabels:
      move2kube.konveyor.io/service: php
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: php
      name: php
    spec:
      containers:
        - image: index.docker.io/myproject/php:latest
          imagePullPolicy: Always
          name: php
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
      securityContext: {}
status: {}
