apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: ruby
  name: ruby
spec:
  replicas: 2
  selector:
    matchLabels:
      move2kube.konveyor.io/service: ruby
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: ruby
      name: ruby
    spec:
      containers:
        - image: index.docker.io/myproject/ruby:latest
          imagePullPolicy: Always
          name: ruby
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
      securityContext: {}
status: {}
