apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: rust
  name: rust
spec:
  ports:
    - name: port-8085
      port: 8085
      targetPort: 8085
  selector:
    move2kube.konveyor.io/service: rust
  type: ClusterIP
status:
  loadBalancer: {}
