move2kube:
  minreplicas: "2"
  services:
    django:
      "8080":
        servicetype: ClusterIP
      enable: true
      port: "8080"
    golang:
      "8080":
        servicetype: ClusterIP
      enable: true
      ports:
        - "8080"
    java-gradle:
      "8080":
        servicetype: ClusterIP
      childModules:
        java-gradle:
          port: "8080"
      dockerfileType: build stage in base image
      enable: true
      wartransformer: Jboss
    java-maven:
      "8080":
        servicetype: ClusterIP
      childModules:
        java-maven:
          port: "8080"
      dockerfileType: build stage in base image
      enable: true
      wartransformer: Jboss
    java-war:
      "8080":
        servicetype: ClusterIP
      enable: true
      wartransformer: Jboss
    nodejs:
      "8080":
        servicetype: ClusterIP
      enable: true
      port: "8080"
    php:
      "8082":
        servicetype: ClusterIP
      enable: true
    python:
      "8080":
        servicetype: ClusterIP
      enable: true
      port: "8080"
    ruby:
      "8080":
        servicetype: ClusterIP
      enable: true
      port: "8080"
    rust:
      "8085":
        servicetype: ClusterIP
      enable: true
      port: "8085"
  target:
    cicd:
      tekton:
        gitrepobasicauthsecret: ""
        gitreposshsecret: ""
        registrypushsecret: ""
    default:
      clustertype: Kubernetes
      ingress:
        host: myproject.com
        ingressclassname: ""
        tls: ""
    imageregistry:
      index.docker.io:
        logintype: no authentication
      namespace: myproject
      url: index.docker.io
  transformers:
    types:
      - ArgoCD
      - Buildconfig
      - CloudFoundry
      - ClusterSelector
      - ComposeAnalyser
      - ComposeGenerator
      - ContainerImagesPushScriptGenerator
      - DockerfileDetector
      - DockerfileImageBuildScript
      - DockerfileParser
      - DotNetCore-Dockerfile
      - EarAnalyser
      - EarRouter
      - Golang-Dockerfile
      - Gradle
      - Jar
      - Jboss
      - Knative
      - Kubernetes
      - KubernetesVersionChanger
      - Liberty
      - Maven
      - Nodejs-Dockerfile
      - OperatorTransformer
      - PHP-Dockerfile
      - Parameterizer
      - Python-Dockerfile
      - ReadMeGenerator
      - Ruby-Dockerfile
      - Rust-Dockerfile
      - Tekton
      - Tomcat
      - WarAnalyser
      - WarRouter
      - WinWebApp-Dockerfile
      - ZuulAnalyser
  transformerselector: ""
