apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: myproject-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: petstoreee7
      name: petstoreee7
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/myproject/petstoreee7:latest
              imagePullPolicy: Always
              name: petstoreee7
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: sponsor-postgresql
      name: sponsor-postgresql
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: postgres:9.6.5
              imagePullPolicy: Always
              name: sponsor-postgresql
              ports:
                - containerPort: 5432
                  protocol: TCP
              resources: {}
          restartPolicy: Always
          securityContext: {}
    status: {}
parameters: []
