
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
    creationTimestamp: null
    name: myproject-clone-build-push
spec:
    params:
        - description: registry-domain/namespace where the output image should be pushed.
          name: image-registry-url
          type: string
    tasks:
        - name: clone-1
          params:
            - name: url
              value: https://github.com/agoncal/agoncal-application-petstore-ee7.git
            - name: revision
              value: master
            - name: deleteExisting
              value: "true"
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: myproject-shared-data
            - name: basic-auth
              workspace: git-basic-auth-credentials
        - name: build-push-1
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/petstoreee7
            - name: DOCKERFILE
              value: Dockerfile
            - name: CONTEXT
              value: .
          runAfter:
            - clone-1
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: myproject-shared-data
            - name: dockerconfig
              workspace: registry-credentials
    workspaces:
        - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
          name: myproject-shared-data
        - description: This workspace provides the credentials (Docker config.json) for pushing images to the registry. See https://hub.tekton.dev/tekton/task/kaniko
          name: registry-credentials
        - description: This workspace provides the credentials (username and password) for cloning the git repo. See https://hub.tekton.dev/tekton/task/git-clone
          name: git-basic-auth-credentials

...
