apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: myproject-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: sponsor-postgresql
      name: sponsor-postgresql
    spec:
      ports:
        - name: port-5432
          port: 5432
          targetPort: 5432
      selector:
        move2kube.konveyor.io/service: sponsor-postgresql
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: myproject
      name: myproject
    spec:
      rules:
        - host: myproject.com
          http:
            paths:
              - backend:
                  service:
                    name: petstoreee7
                    port:
                      name: port-8080
                path: /petstoreee7
                pathType: Prefix
              - backend:
                  service:
                    name: sponsor-postgresql
                    port:
                      name: port-5432
                path: /sponsor-postgresql
                pathType: Prefix
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: petstoreee7
      name: petstoreee7
    spec:
      replicas: ${{COMMON_REPLICAS}}
      selector:
        matchLabels:
          move2kube.konveyor.io/service: petstoreee7
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            move2kube.konveyor.io/service: petstoreee7
          name: petstoreee7
        spec:
          containers:
            - image: quay.io/myproject/petstoreee7:latest
              imagePullPolicy: Always
              name: petstoreee7
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: petstoreee7
      name: petstoreee7
    spec:
      ports:
        - name: port-8080
          port: 8080
          targetPort: 8080
      selector:
        move2kube.konveyor.io/service: petstoreee7
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: sponsor-postgresql
      name: sponsor-postgresql
    spec:
      replicas: ${{COMMON_REPLICAS}}
      selector:
        matchLabels:
          move2kube.konveyor.io/service: sponsor-postgresql
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            move2kube.konveyor.io/service: sponsor-postgresql
          name: sponsor-postgresql
        spec:
          containers:
            - image: postgres:9.6.5
              imagePullPolicy: Always
              name: sponsor-postgresql
              ports:
                - containerPort: 5432
                  protocol: TCP
              resources: {}
          restartPolicy: Always
          securityContext: {}
    status: {}
parameters:
  - name: COMMON_REPLICAS
    value: "2"
