patches:
  - path: apps-v1-deployment-petstoreee7.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: petstoreee7
  - path: apps-v1-deployment-sponsor-postgresql.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: sponsor-postgresql
resources:
  - ../../base
