apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: java-gradle
  name: java-gradle
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: index.docker.io/myproject/java-gradle:latest
          imagePullPolicy: Always
          name: java-gradle
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
